### ISSUE TITLE
Update Genepop functions to call on 'genepop' package

### ISSUE THREAD

**Issue by krshedd** [krshedd/GCL-R-Scripts#14]
Tyler found the 'genepop' package so that we can run Genepop without having to leave R. We can update our current .gcl functions to create a wrapper that goes from .gcl to genepop.txt, calls on the 'genepop' package, and then reads in the Geneopop output files (.P,, etc.) back in to R.

**Comment by awbarclay** [comment]
This is a pretty old issue, should I close it? I never saw the benefit of running genepop through R.  The genepop package just runs genepop.exe using R, meanwhile you can't use R because genepop is running.

**Comment by krshedd** [comment]
Eh, fair enough. I use the `genepop` package fairly often in R, but I see your point, especially with large baselines.

**Comment by csjalbert** [comment]
https://blog.rstudio.com/2019/03/14/rstudio-1-2-jobs/
Have you messed with jobs - its next to your console and I think is for just that. From the link: "You can use these to run your scripts in the background while you continue to use the IDE"

I haven't messed with it yet.

**Comment by krshedd** [comment]
Whoa, very cool, didn’t know about that. Not sure how it works with a single baseline Notebook though.

**Comment by csjalbert** [comment]
I gave a quick read - you can load from global environment and continue on, but yes if the next step relies on the output then it's not overly useful. Also, doing that 'can be slow with large environments'. Granted, that article is 2019 so there could have been updates. 

back to genepop - I like the idea of running within R. It does make it unusable but I feel like its a bit easier to take notes, etc., about the run.

**Comment by krshedd** [comment]
Agreed, but perhaps given Andy’s concerns we should close the issue and let users decide on their own? Fortunately either way makes output files that can be read back in to R with the same ReadHWE or ReadDis files.

**Comment by krshedd** [comment]
Closing this issue since I do not think it is relevant to `GCLr`. We already have functions for **pairwise Fst** and **LD** that are basically wrappers for functions in the `genepop` package. I do not think that we need a wrapper for **HWE** since that workflow is already pretty straightfoward:

`GCLr::gcl2genepop(sillyvec = sillyvec, loci = loci, path = "~/test.gen.txt`
`genepop::test_HW(inputFile = "C:/Users/krshedd/Documents/R/test.gen.txt")   # needs full file path`
`genepop_hwe <- GCLr::read_genepop_hwe(file = "~/R/test.gen.txt.P", sillyvec = sillyvec)`
