### ISSUE TITLE
PoolCollections.GCL grabs attribute by rowname, not matching FK_FISH_ID

### ISSUE THREAD

**Issue by krshedd** [krshedd/GCL-R-Scripts#20]
This function assumes that `rownames(attributes) == attributes$FK_FISH_ID`, they may not and it should either force this behavior before matching attributes or toss an error message letting the user know.

**Comment by csjalbert** [comment]
@krshedd - I just saw this. Is it safe to assume this is in reference to the OG function and we can close it or do we need to update the static branch?

**Comment by awbarclay** [comment]
Since the comment was back in 2017 and it's talking about the attributes, I think it's safe to assume that its referring to the old function.  I don't think we need to update the static branch.

**Comment by krshedd** [comment]
Agreed, this was in reference to the OG function, we can close this issue as it is no longer relevant.

**Comment by csjalbert** [comment]
Perfect - I realized there are a few other similar issues (old) posted so we can probably close those too.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by krshedd** [comment]
Awesome, feel free to go an close out the obsolete issues, thanks

**Comment by csjalbert** [comment]
Closing as this references old functions, now housed in the v1.12.0-static branch. Not an issue with new functions.
