### ISSUE TITLE
Anderson_etal can't handle haploid markers

### ISSUE THREAD

**Issue by krshedd** [krshedd/GCL-R-Scripts#21]
The function bombs on haploid markers. Either needs an if/stop to warn users or needs to be adapted to incorporate haploid markers.

**Comment by awbarclay** [comment]
I assume that this issue can be closed. Is this function still relevant now that we are using rubias?  There is no documentation to explain what it does.

**Comment by krshedd** [comment]
Yes, this can be closed

**Comment by awbarclay** [comment]
Old issue, no need to keep issue open.
