### ISSUE TITLE
QC.R alternate species check issue

### ISSUE THREAD

**Issue by awbarclay** [krshedd/GCL-R-Scripts#25]
The alternate species code (lines 186-201)  does not not assign "Not applicable" to alternate object when project loci do not contain the loci needed for alternate species check.

Error in FindAlternateSpecies.GCL(sillyvec = ProjectSillys, species = species) : 
  None of the 'AlternateMarkers' found in 'loci', hoser!!!

**Comment by csjalbert** [comment]
Closing - I fixed this in the new package function. It now searches for species and specific loci then performs the alt species check.
