### ISSUE TITLE
QC.R problem reading in GTseq QC data

### ISSUE THREAD

**Issue by awbarclay** [krshedd/GCL-R-Scripts#29]
First of all, I was using QC.R on the development branch.  I was doing a QC for Chinook GT-Seq project K144, and I ran into a problem when reading in the QC genotypes.  The logical in the first if statement at line 103 "max(nalleles) <=2" was TRUE which made it use the ReadBiomarkQC.GCL function instead of the ReadGTseqQC.GCL function.  As a workaround, I ran line 109 independently and it worked fine.

**Comment by krshedd** [comment]
Do you have any proposed solutions? Should we just include a logical statement at the top of the script such as `project_type = "SNP"` (or "uSat", or "GT-seq")? That would eliminate the need for guessing based on LocusControl.

**Comment by awbarclay** [comment]
Yes, I think a logical statement would be the best solution.  I like your suggestion, I was thinking the same thing.

Andy

**Comment by krshedd** [comment]
Sounds good, I can go ahead and do that then on the develop branch.
