### ISSUE TITLE
RemoveDups.GCL error if you pass empty dupcheck

### ISSUE THREAD

**Issue by csjalbert** [krshedd/GCL-R-Scripts#35]
I ran an entire chunk, so didn't look at the empty dupcheck object before feeding to this function. But the remove dups function fails if the duplicates object is empty:

Error in allsillys[sapply(dupcheck, function(dc) { :   invalid subscript type 'list',
Maybe just a warning at the top:

`If ( length(dupcheck) = 0){
 print("no duplicates to remove")
} else { 
....function...
}`

**Comment by krshedd** [comment]
Hey @awbarclay , do you want to fix this real quick?

**Comment by awbarclay** [comment]
Yep, I'll get on it.

**Comment by awbarclay** [comment]
A new stop message has been added to RemoveDups.GCL.
