### ISSUE TITLE
old rubias baseline loci name issue

### ISSUE THREAD

**Issue by csjalbert** [krshedd/GCL-R-Scripts#37]
I realized old rubias baselines are not compatible with newly created rubias mixtures. When you use an old baseline with a new mixture file, run_rubias_mixture() tosses:
```
Error in rubias::infer_mixture(reference = reference, mixture = mixture,  : 
  reference and mixture data frames differ in structure; check # of columns and variable names
```

All loci names in the old baselines were converted from hyphens to periods, at some point (e.g., One_agt.132 vs One_agt-132), so the names appear different. Perhaps we should check names [for periods?] and toss a message asking if the user is using an old baseline?

**Comment by awbarclay** [comment]
Checking for periods won't work because some loci have periods.  How about adding a check before infer_mixture to see if the headers match between the mixture and baseline?  If they don't match, a stop message is spit out saying something similar to the infer_mixture error and then an additional question about whether you are using an old baseline.

**Comment by csjalbert** [comment]
> 
> 
> Checking for periods won't work because some loci have periods. How about adding a check before infer_mixture to see if the headers match between the mixture and baseline? If they don't match, a stop message is spit out saying something similar to the infer_mixture error and then an additional question about whether you are using an old baseline.

Ya, I figured that wasn't the solution. This sounds like a good solution to me. At least gives the user an idea of the possible issue.

**Comment by awbarclay** [comment]
Ok, I'm on it!

**Comment by awbarclay** [comment]
Added stop message if reference and mixture headers differ.
