### ISSUE TITLE
LeaveOneOutDist.GCL fails with fixed markers

### ISSUE THREAD

**Issue by tylerdann** [krshedd/GCL-R-Scripts#4]
Running the function with a marker that is fixed in all pops causes the function to drop bombs like Hiroshima:
 Error in dmultinom(x = x[locus, 1:nalleles[locus]], size = ploidy[locus],  : 
  probabilities must be finite, non-negative and not all 0 
7 stop("probabilities must be finite, non-negative and not all 0") 
6 dmultinom(x = x[locus, 1:nalleles[locus]], size = ploidy[locus], 
    prob = theta[locus, 1:nalleles[locus]]) at LeaveOneOutDist.GCL.r#113
5 FUN(X[[i]], ...) 
4 lapply(X = X, FUN = FUN, ...) 
3 sapply(loci[NAind], function(locus) {
    2 \* dmultinom(x = x[locus, 1:nalleles[locus]], size = ploidy[locus], 
        prob = theta[locus, 1:nalleles[locus]])
}) at LeaveOneOutDist.GCL.r#113
2 genofunc(x = x, theta = array(data = theta[silly2, 1:nloci, 1:max(nalleles)], 
    dim = c(nloci, max(nalleles)), dimnames = list(c(loci), paste("Allele", 
        seq(max(nalleles))))), NAind) at LeaveOneOutDist.GCL.r#130
1 LeaveOneOutDist.GCL(c("KCHUI09", "KCOAL10", "KSUCKCR11", "KTALA08", 
    "KTHEO12"), LocusControl$locusnames, 1:5, pgroup = rep(1/5, 
    5)) 
As Kyle said, you can't draw from a multinomial distribution that doesn't exist. Please add an if then that filters out fixed markers.

**Comment by krshedd** [comment]
Maybe instead of adding an if statement withing LeaveOneOutDist.GCL, we should just create a separate function to return a vector of non-fixed loci? Then you can feed that vector of loci into LeaveOneOutDist.GCL or other functions? Thoughts?
