### ISSUE TITLE
RemoveDups.GCL

### ISSUE THREAD

**Issue by csjalbert** [krshedd/GCL-R-Scripts#40]
note to rethink after inseason analysis - what about output empty tibble along with the warning saying nothing in dupcheck. 

Reason: I have generalized scripts where I save objects and an empty tibble would allow me to just click through without re-working the script each week.

**Comment by awbarclay** [comment]
I'll make RemoveDups.GCL output an empty tibble and spit out a warning message if no dups are removed.

**Comment by awbarclay** [comment]
I updated RemoveDups.GCL with a warning and outputs an empty data frame if dupcheck is empty.
