### ISSUE TITLE
save_objects msg

### ISSUE THREAD

**Issue by csjalbert** [krshedd/GCL-R-Scripts#47]
The new save_objects flag (rds = TRUE) prints out the object name and NULL. 
Do we need the print out? I was working with the new funs this morning and got confused by the NULL printout - I assumed it was not working, or the object was empty but it seems to be fine. 

Example: 
```
iris <- iris  # bringing into pos = 1
save_objects(objects = "iris", path = "Objects", rds = FALSE)
>$iris
>NULL
```

**Comment by awbarclay** [comment]
No, we don't need it.  It was the sapply that returned the object name and NULL.  I assigned the sapply to a bogus object name so nothing will be printed out.  This should take care of the issue.
