### ISSUE TITLE
QC.R typos

### ISSUE THREAD

**Issue by csjalbert** [krshedd/GCL-R-Scripts#48]
@krshedd  - Andy and I figured you'd be the best person to clarify the text comment for the `QCSummaryfile` input object... it seems like a typo. Should the comment read "Do **not** name normal ..." Maybe something like "don't change this or it will not append to the QC summary"  

`QCSummaryfile <- paste("Project", project,"QC Summary R Script.xlsx") #  Do name normal summary file!!! If you do, it will overwrite it, not append it`

**Comment by krshedd** [comment]
Ya, that is a typo. However, hopefully when we re-do the QC, we won’t need either .xlsx file anymore since we are switching to using an R Notebook.

**Comment by csjalbert** [comment]
closing as this is not in the package QC function
