### ISSUE TITLE
read_project_genotypes update

### ISSUE THREAD

**Issue by csjalbert** [krshedd/GCL-R-Scripts#49]
Whoever gets to this one first - it looks like this hasn't been updated to newest tidy. I got this when I sourced it in QC.R:

`Note: Using an external vector in selections is ambiguous.
i Use `all_of(attnames)` instead of `attnames` to silence this message.
i See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>.`

**Comment by awbarclay** [comment]
Chase, I'm pretty busy with my proposal right now.  Can you take care of this?  If not, I'll get to it when I have time.

**Comment by csjalbert** [comment]
@awbarclay - no worries and yes, will do whenever I have time. This is not pressing I just wanted to leave a note somewhere so we remembered. Found it when trying to get through the Lynn Canal QC.

**Comment by csjalbert** [comment]
closing - this function is undergoing heavy maintenance in the package version and warning is already fixed.
