### ISSUE TITLE
new2old %dopar%

### ISSUE THREAD

**Issue by csjalbert** [krshedd/GCL-R-Scripts#51]
During the first run I got:
`Error in foreach::foreach(silly = sillyvec_, .packages = c("tidyverse", : could not find function "%dopar%"`

Seems like I was missing something, so I added `foreach` package to the p_load line at the top and rebooted R - Seems to be working now, do we need to specify this package or how was it working for you @awbarclay ?

**Comment by awbarclay** [comment]
I added the missing packages. %dopar%  made it bomb because I don't know how to make the package for that explicit.
