### ISSUE TITLE
old2new_gcl.GCL incorrect col types

### ISSUE THREAD

**Issue by csjalbert** [krshedd/GCL-R-Scripts#58]
This function does not generate the same col types as LOKI2R. It works fine, generally, but pooling converted gcl objects with normal gcl objects fails with:
`Can't combine ..1$DNA_TRAY_WELL_CODE <character> and ..2$DNA_TRAY_WELL_CODE <double>.`

I need to modify this to match columns used by LOKI2R.

**Comment by csjalbert** [comment]
@awbarclay  and @krshedd - after looking at this further, it appears that we manually coded the column types for each attribute. Do you remember why we did this and do you see any issue with matching to LOKI2R col types?

**Comment by awbarclay** [comment]
I think the col_types were hard coded because some columns will get treated as logical depending on the data that is in Loki.  I don’t see any problem with using the same col_types as LOKI2R.

**Comment by csjalbert** [comment]
Thanks @awbarclay , this was fixed with fb62974
