### ISSUE TITLE
 stratified_estimator_rubias.R cv issue

### ISSUE THREAD

**Issue by csjalbert** [krshedd/GCL-R-Scripts#59]
Adding a note to look at this function later - The argument cv = xx, does not work in my existing seine 2021 analysis. The code works with the default cv = NULL, but when I add values, it tosses the error below. I haven't gotten into it but assume it's something to do with changing groups since `McDonald` is one of the groups in `group_names`.

Error:
"Error: Can't subset columns that don't exist. x Column `McDonald` doesn't exist."

This code works fine:
`stratified_estimator_rubias(path = rubias_out_path, 
                            mixvec = strata_names_2021[1:3],
                            group_names = groups_7_klawock,
                            catchvec = c(34860, 38169, 21562),
                            newname = "D101_21_stratified_NB",
                            group_names_new = groups_4_NB,
                            groupvec_new = c(1, 2, 3, 4, 1, 1, 1),
                            alpha = 0.1, 
                            burn_in = 5000,
                            bias_corr = TRUE`

**Comment by krshedd** [comment]
Bobby addressed this on `develop`, but since we haven't merged into `master` it is still open. I'm closing manually.
