### ISSUE TITLE
Format of StratifiedEstimator.GCL output doesn't match CustomCombineBAYESOutput.GCL

### ISSUE THREAD

**Issue by krshedd** [krshedd/GCL-R-Scripts#7]
## Problem

The output from `StratifiedEstimator.GCL` is inconsistent with what we get from `CustomCombineBAYESOutput.GCL`.

`CustomCombineBAYESOutput.GCL` returns a list with `Stats` and `Output` for each mixture/silly
The `dimnames` for `Stats` are:
- Rows = `groupnames`
- Columns = "mean"   "sd"     "median" "5%"     "95%"    "P=0"    "GR"

On the other hand, `StratifiedEstimator.GCL` returns a list with `Summary` and `Output` for each mixture/silly
The `dimnames` for `Summary` are:
- Rows = `groupnames`
- Columns = "MEAN"   "SD"     "5%"     "MEDIAN" "95%"    "P0"     "GR"

This is both annoying and problematic that `Stats` and `Summary` don't have the same column names or positions. I think it would be beneficial if both of these commonly used functions had similar output, but want to check with everyone first since these functions are crucial to everyone's work.
## Potential Solutions
1. Do nothing
   - Everyone deals with this on their own as we do now.
2. Partial change
   - Within `StratifiedEstimator.GCL`, change `Summary` to `Stats`
   - Within `StratifiedEstimator.GCL`, change the column **names** for `Stats` so they match `CustomCombineBAYESOutput.GCL`, but do NOT change their relative **position** so that:
     - Columns = "mean"   "sd"     "5%"     "median" "95%"    "P=0"     "GR"
   - This would mean that if you call output from `StratifiedEstimator.GCL` or `CustomCombineBAYESOutput.GCL` by **name**, you would get the same result. The benefit to this is that if anyone already has recycled code that "re-sorts" the columns from `StratifiedEstimator.GCL` to `CustomCombineBAYESOutput.GCL`, and then calls by **position** that will be fine.
3. Complete change
   - Within `StratifiedEstimator.GCL`, change `Summary` to `Stats`
   - Within `StratifiedEstimator.GCL`, change the column **names** and **position** for `Stats` so they exactly match `CustomCombineBAYESOutput.GCL`:
     - Columns = "mean"   "sd"     "median" "5%"     "95%"    "P=0"    "GR"
   - This would mean that if you call output from `StratifiedEstimator.GCL` or `CustomCombineBAYESOutput.GCL` by **name** or **position**, you would get the same result. The potential danger with this is that if you have old code that calls by **positon**, you will need to modify that code so you make sure you are getting the "median" as opposed to "5%". Make sense?

Please weigh in by "commenting" on this issue so everyone can see the conversation. No changes will be made until everyone weighs in.

**Comment by jim-jasper** [comment]
Trivial fix. Recommend to always call by name.

**Comment by krshedd** [comment]
Thanks for commenting Jim, but your response is unclear. I presume you are advocating that we go with change option 3 and modify `StratifiedEstimator.GCL` so it gives the same output as `CustomCombineBAYESOutput.GCL`. If so and we do make changes, it is important for everyone to be aware when they recycle code. I agree that it is always best practice to call by name, but I'm not sure everyone does.

Also, semantics, but issues do not get closed until code is written that fixes them. The only other reason to close an issue is if you don't think it needs addressing (i.e. option 1: do nothing).

**Comment by srolive** [comment]
I think a partial change is probably the safest bet, but it would be cleaner to make them both match exactly. I do not use stratified estimator enough to have a strong opinion either way, other than I think a change should be made.

**Comment by awbarclay** [comment]
Yes, I think we should make the names consistent between the two outputs.  I always call these by name because I've been burned in the past when calling by position.  I used the stratified estimator in Cook Inlet and I have found it annoying that the names are different than the custom combine function.

**Comment by tylerdann** [comment]
I agree.  We change the function so that it parallels CustomCombine and we
can all call by name to be safe.  Who should make the change?  Jim?
